import React, { useState, useEffect } from 'react';
import { BlogPost } from '../types';
import { blogService } from '../services/database';

interface BlogProps {
  onBack: () => void;
}

export const Blog: React.FC<BlogProps> = ({ onBack }) => {
  const [posts, setPosts] = useState<BlogPost[]>([]);
  const [selectedPost, setSelectedPost] = useState<BlogPost | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const unsubscribe = blogService.subscribeToPosts((fetchedPosts) => {
      setPosts(fetchedPosts);
      setLoading(false);
    });
    return () => unsubscribe();
  }, []);

  const handlePostClick = (post: BlogPost) => {
    setSelectedPost(post);
    blogService.incrementView(post.id);
    window.scrollTo(0, 0);
  };

  const formatDate = (ts: number) => {
    return new Date(ts).toLocaleDateString('pt-BR', {
      day: 'numeric', month: 'long', year: 'numeric'
    });
  };

  // --- SINGLE POST VIEW ---
  if (selectedPost) {
    return (
      <div className="min-h-screen bg-gray-50 pb-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8">
          <button 
            onClick={() => setSelectedPost(null)}
            className="flex items-center text-sm text-gray-500 hover:text-brand-600 mb-6 transition-colors"
          >
            <svg className="w-4 h-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Voltar para o Blog
          </button>

          <article className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
            {/* Header Image */}
            <div className="h-64 sm:h-96 w-full relative bg-gray-100 flex items-center justify-center overflow-hidden">
              <img 
                src={selectedPost.imageUrl} 
                alt={selectedPost.title} 
                className="w-full h-full object-contain p-4"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent"></div>
              <div className="absolute bottom-6 left-6 right-6">
                <div className="flex gap-2 mb-3">
                  {selectedPost.tags.map(tag => (
                    <span key={tag} className="px-2 py-1 bg-brand-500/90 text-white text-xs font-bold uppercase tracking-wider rounded">
                      {tag}
                    </span>
                  ))}
                </div>
                <h1 className="text-2xl sm:text-4xl font-bold text-white shadow-sm leading-tight">
                  {selectedPost.title}
                </h1>
                <p className="text-gray-200 text-sm mt-2 font-medium">
                  Publicado em {formatDate(selectedPost.publishedAt)}
                </p>
              </div>
            </div>

            {/* Content */}
            <div className="p-6 sm:p-10 lg:p-12">
              <div 
                className="prose prose-lg prose-blue max-w-none text-gray-700 
                  prose-headings:font-bold prose-headings:text-gray-900 
                  prose-a:text-brand-600 prose-a:no-underline hover:prose-a:underline
                  prose-img:rounded-xl"
                dangerouslySetInnerHTML={{ 
                   // Inject affiliate link into '#' placeholders generated by AI
                   __html: selectedPost.content.replace(/href="#"/g, `href="${selectedPost.affiliateUrl}" target="_blank" rel="sponsored"`) 
                }} 
              />
            </div>

            {/* Footer CTA */}
            <div className="bg-gray-50 p-8 text-center border-t border-gray-100">
               <h3 className="text-xl font-bold text-gray-900 mb-2">Gostou deste produto?</h3>
               <p className="text-gray-600 mb-6">Confira o preço atual e garanta o seu com desconto.</p>
               <a 
                 href={selectedPost.affiliateUrl} 
                 target="_blank" 
                 rel="sponsored"
                 className="inline-block px-8 py-4 bg-green-600 hover:bg-green-700 text-white text-lg font-bold rounded-lg shadow-lg transform transition hover:scale-105"
               >
                 Ver Oferta na Loja
               </a>
            </div>
          </article>
        </div>
      </div>
    );
  }

  // --- BLOG LIST VIEW ---
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <div className="bg-brand-600 py-16 px-4 sm:px-6 lg:px-8 text-center">
        <h1 className="text-3xl font-extrabold text-white sm:text-4xl">
          Blog de Ofertas & Reviews
        </h1>
        <p className="mt-4 text-xl text-brand-100 max-w-2xl mx-auto">
          Análises detalhadas, dicas de uso e as melhores oportunidades selecionadas para você.
        </p>
        <button onClick={onBack} className="mt-8 px-6 py-2 bg-white/10 hover:bg-white/20 text-white rounded-full text-sm font-medium transition-colors border border-white/30">
          ← Voltar para a Loja
        </button>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {loading ? (
          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
             {[1,2,3].map(i => (
               <div key={i} className="animate-pulse">
                 <div className="bg-gray-200 h-48 rounded-xl mb-4"></div>
                 <div className="h-4 bg-gray-200 rounded w-3/4 mb-2"></div>
                 <div className="h-4 bg-gray-200 rounded w-1/2"></div>
               </div>
             ))}
          </div>
        ) : posts.length === 0 ? (
          <div className="text-center py-20 text-gray-500">
            <p className="text-lg">Ainda não há posts. Os reviews serão gerados automaticamente em breve!</p>
          </div>
        ) : (
          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
            {posts.map((post) => (
              <div 
                key={post.id} 
                className="group flex flex-col bg-white border border-gray-200 rounded-2xl overflow-hidden hover:shadow-xl transition-all duration-300 cursor-pointer"
                onClick={() => handlePostClick(post)}
              >
                <div className="h-48 overflow-hidden bg-gray-100 relative">
                  <img 
                    src={post.imageUrl} 
                    alt={post.title} 
                    className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
                  />
                </div>
                <div className="flex-1 p-6 flex flex-col">
                  <div className="flex gap-2 mb-3">
                    {post.tags.slice(0, 2).map(tag => (
                      <span key={tag} className="text-[10px] font-bold uppercase tracking-wider text-brand-600 bg-brand-50 px-2 py-1 rounded">
                        {tag}
                      </span>
                    ))}
                  </div>
                  <h3 className="text-xl font-bold text-gray-900 mb-2 group-hover:text-brand-600 transition-colors line-clamp-2">
                    {post.title}
                  </h3>
                  <p className="text-gray-500 text-sm mb-4 line-clamp-3 flex-1">
                    {post.excerpt}
                  </p>
                  <div className="mt-auto flex items-center justify-between pt-4 border-t border-gray-100">
                    <span className="text-xs text-gray-400 font-medium">
                      {formatDate(post.publishedAt)}
                    </span>
                    <span className="text-sm font-semibold text-brand-600 group-hover:translate-x-1 transition-transform inline-flex items-center">
                      Ler mais →
                    </span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};